from collections import defaultdict
from concurrent.futures import ThreadPoolExecutor, as_completed
from typing import Any, Dict, List, Tuple

from ContractCoding.config import Config
from ContractCoding.memory.audit import check_missing_specs
from ContractCoding.memory.document import DocumentManager
from ContractCoding.memory.processor import MemoryProcessor
from ContractCoding.orchestration.runner import AgentRunner
from ContractCoding.review.gate import ReviewGate
from ContractCoding.scheduler.dispatch import SchedulerDispatchBuilder
from ContractCoding.utils.log import get_logger
from ContractCoding.utils.state import GeneralState


class GraphTraverser:
    def __init__(
        self,
        config: Config,
        agent_runner: AgentRunner,
        memory_processor: MemoryProcessor,
        document_manager: DocumentManager,
    ):
        self.config = config
        self.logger = get_logger(config.LOG_PATH)
        self.agent_runner = agent_runner
        self.memory_processor = memory_processor
        self.termination_policy = self.config.TERMINATION_POLICY
        self.document_manager = document_manager
        self.dispatch_builder = SchedulerDispatchBuilder()
        self.review_gate = ReviewGate()

    def traverse(
        self, start_agent: str, initial_states: Any
    ) -> Tuple[List[Dict[str, List[GeneralState]]], List[Tuple[str, str]], List[GeneralState]]:
        execution_trace: List[Tuple[str, str]] = []
        initial_state_list = initial_states if isinstance(initial_states, list) else [initial_states]
        all_layers: List[Dict[str, List[GeneralState]]] = [{start_agent: initial_state_list}]
        terminating_states: List[GeneralState] = []

        executed_agents_history = []

        while all_layers[-1] and len(all_layers) <= self.config.MAX_LAYERS:
            current_level_agents = all_layers[-1]
            layer_index = len(all_layers) - 1

            base_version = self.document_manager.get_version()
            try:
                self.document_manager.begin_layer_aggregation(base_version)
            except Exception:
                pass

            layer_executed_agents = []
            layer_output_states: Dict[str, List[GeneralState]] = defaultdict(list)

            def _run_single(agent_name: str, state: GeneralState) -> GeneralState:
                next_available_agents = self.agent_runner.agents
                print(f"--- Current Agent: {agent_name} ---")
                self.logger.info(f"--- Current Agent: {agent_name} | Sub Task: {state.sub_task} ---")
                output_state = self.agent_runner.run(
                    agent_name=agent_name,
                    state=state,
                    next_available_agents=next_available_agents,
                )
                self.memory_processor.add_message(agent_name, output_state)
                execution_trace.append((agent_name, "NEXT_LAYER"))
                return output_state

            max_workers = getattr(self.config, "MAX_WORKERS", 16)
            with ThreadPoolExecutor(max_workers=max_workers) as executor:
                futures = {}
                for agent_name, states in current_level_agents.items():
                    for state in states:
                        futures[executor.submit(_run_single, agent_name, state)] = (agent_name, state)

                for future in as_completed(futures):
                    agent_name, fallback_state = futures[future]
                    layer_executed_agents.append(agent_name)
                    try:
                        output_state = future.result()
                        layer_output_states[agent_name].append(output_state)
                    except Exception as e:
                        self.logger.error(f"Agent {agent_name} failed with error: {e}")
                        layer_output_states[agent_name].append(fallback_state)

            try:
                self.document_manager.commit_layer_aggregation()
            except Exception as e:
                self.logger.error(f"Document layer aggregation commit failed: {e}")

            executed_agents_history.append(set(layer_executed_agents))

            next_level_agents_map = defaultdict(list)
            doc_content = self.document_manager.get()

            if layer_index == 0:
                next_agent = "Architect"
                task_msg = (
                    "Contract review ONLY (no implementation review). Review and repair the Project Plan and Architecture generated by Project Manager. "
                    "Ensure contracts are clear, complete, internally consistent, and describe end-to-end runnable flows (including game loop, systems, and UI wiring). "
                    "Do NOT set any file Status to VERIFIED or DONE during this phase. "
                    "If the contract has blocking issues, set the affected file blocks to ERROR and append actionable issue bullets after the Status line."
                )

                is_valid, validation_errors = self._validate_project_structure(doc_content)
                if not is_valid:
                    self.logger.warning(f"--- Document Validation Failed: {validation_errors} ---")
                    self.logger.info("--- Fallback: Scheduling Project_Manager to fix document structure ---")
                    pm_msg = f"Critical: The Collaborative Document is incomplete. The following files listed in 'Project Structure' are missing from 'Sub-Tasks' or lack required fields: {validation_errors}. You MUST fix the document using `document_action` to add detailed sub-tasks for these files."

                    pm_state = list(current_level_agents.values())[0][0]
                    new_state = GeneralState(
                        task=pm_state.task,
                        sub_task=pm_msg,
                        role="user",
                        thinking="",
                        output="",
                    )
                    next_level_agents_map["Project_Manager"].append(new_state)
                else:
                    pm_state = list(current_level_agents.values())[0][0]
                    new_state = GeneralState(
                        task=pm_state.task,
                        sub_task=task_msg,
                        role="user",
                        thinking="",
                        output="",
                    )
                    next_level_agents_map[next_agent].append(new_state)

            elif layer_index == 1:
                next_level_agents_map = self._schedule_from_contract(doc_content, current_level_agents)
            else:
                next_level_agents_map = self._schedule_from_contract(doc_content, current_level_agents)

            if not next_level_agents_map:
                pending_tasks = [t for t in self._parse_contract(doc_content) if t['status'] != 'VERIFIED']

                if not pending_tasks:
                    terminal_source = layer_output_states or current_level_agents
                    for states in terminal_source.values():
                        terminating_states.extend(states)
                    break
                else:
                    in_progress_tasks = [t for t in pending_tasks if t['status'] == 'IN_PROGRESS']

                    if in_progress_tasks and not next_level_agents_map:
                        base_state = self._select_base_state(layer_output_states, current_level_agents)
                        for task in in_progress_tasks:
                            owner = task['owner']
                            file_path = task['file']
                            if owner != "Unknown":
                                msg = f"Continue implementation of {file_path}. Current Status: IN_PROGRESS. You MUST complete the logic."
                                new_state = base_state.model_copy()
                                new_state.sub_task = msg
                                next_level_agents_map[owner].append(new_state)

                    if not next_level_agents_map:
                        pm_msg = "Critical: The workflow has stalled. There are pending tasks but no agents were scheduled. Please review the 'Symbolic API Specifications' in the document. Ensure all files have valid Status (TODO, IN_PROGRESS, DONE, VERIFIED) and Owners."
                        base_state = self._select_base_state(layer_output_states, current_level_agents)
                        new_state = base_state.model_copy()
                        new_state.sub_task = pm_msg
                        next_level_agents_map["Project_Manager"].append(new_state)

            next_layer_plan = {k: len(v) for k, v in next_level_agents_map.items()}
            print(f"--- Next Layer Agents: {next_layer_plan} ---")
            self.logger.info(f"--- Next Layer Plan: {next_layer_plan} ---")
            all_layers.append(next_level_agents_map)

        return all_layers, execution_trace, terminating_states

    def _select_base_state(
        self,
        output_states: Dict[str, List[GeneralState]],
        fallback_states: Dict[str, List[GeneralState]],
    ) -> GeneralState:
        for states in output_states.values():
            if states:
                return states[0]
        for states in fallback_states.values():
            if states:
                return states[0]
        return GeneralState()

    def _validate_project_structure(self, content: str) -> Tuple[bool, List[str]]:
        validation_errors = self.document_manager.validate_contract_structure()
        if validation_errors:
            return False, validation_errors

        return True, []

    def _parse_contract(self, content: str) -> List[Dict[str, str]]:
        return self.document_manager.get_tasks()

    def _schedule_from_contract(
        self, doc_content: str, current_layer_agents: Dict[str, List[GeneralState]]
    ) -> Dict[str, List[GeneralState]]:
        missing_specs = check_missing_specs(doc_content)
        next_agents_map = defaultdict(list)

        base_state = list(current_layer_agents.values())[0][0]

        if missing_specs:
            pm_msg = f"Critical: The Collaborative Document is incomplete. The following files listed in 'Project Structure' are missing from 'Sub-Tasks' or lack required fields: {missing_specs}. You MUST fix the document using `document_action` to add detailed sub-tasks for these files."
            new_state = base_state.model_copy()
            new_state.sub_task = pm_msg
            next_agents_map["Project_Manager"].append(new_state)
            return next_agents_map

        tasks = self._parse_contract(doc_content)
        if not tasks:
            pm_msg = "Critical: The system could not parse any tasks from the 'Symbolic API Specifications'. Please ensure the document follows the correct format with '**File:**', '**Owner:**', and '**Status:**' fields."
            new_state = base_state.model_copy()
            new_state.sub_task = pm_msg
            next_agents_map["Project_Manager"].append(new_state)
            return next_agents_map

        incomplete_tasks = []
        for t in tasks:
            file_path = t.get('file', 'Unknown')
            owner = t.get('owner', 'Unknown')
            status = t.get('status', 'TODO')
            missing_fields = []
            if owner == 'Unknown':
                missing_fields.append('Owner')
            if status not in ['TODO', 'IN_PROGRESS', 'ERROR', 'DONE', 'VERIFIED']:
                missing_fields.append(f"Status({status})")
            if missing_fields and file_path != 'Unknown':
                incomplete_tasks.append(f"{file_path}: {', '.join(missing_fields)}")

        if incomplete_tasks:
            pm_msg = (
                "Critical: The Collaborative Document has incomplete sub-tasks (missing required fields). "
                f"Fix these file blocks to include **Owner:** and **Status:** (and keep them consistent): {incomplete_tasks}. "
                "You MUST fix the document using `document_action`."
            )
            new_state = base_state.model_copy()
            new_state.sub_task = pm_msg
            next_agents_map["Project_Manager"].append(new_state)
            return next_agents_map

        module_plans = self.document_manager.get_module_plans()
        blocked_tasks: List[Dict[str, object]] = []

        for plan in module_plans:
            ready_by_owner: Dict[str, List[Dict[str, object]]] = defaultdict(list)
            for task in plan.ready_tasks:
                owner = str(task.get("owner", "Unknown"))
                if owner == "Unknown":
                    continue
                ready_by_owner[owner].append(task)

            for owner, owner_tasks in ready_by_owner.items():
                msg = self.dispatch_builder.build_module_owner_packet(plan.name, owner, owner_tasks)
                new_state = base_state.model_copy()
                new_state.sub_task = msg
                next_agents_map[owner].append(new_state)

            for agent_name, review_states in self.review_gate.schedule_reviews(plan, base_state).items():
                next_agents_map[agent_name].extend(review_states)

            if not plan.ready_tasks and not plan.review_tasks and plan.blocked_tasks:
                blocked_tasks.extend(plan.blocked_tasks)

        if not next_agents_map and blocked_tasks:
            pm_msg = self.dispatch_builder.build_blocked_workflow_message(blocked_tasks)
            new_state = base_state.model_copy()
            new_state.sub_task = pm_msg
            next_agents_map["Project_Manager"].append(new_state)

        return next_agents_map


Orchestrator = GraphTraverser
