from collections import defaultdict
from concurrent.futures import ThreadPoolExecutor, as_completed
import re
from typing import Any, Dict, List, Tuple

from ContractCoding.config import Config
from ContractCoding.memory.document import DocumentManager
from ContractCoding.memory.processor import MemoryProcessor
from ContractCoding.orchestration.runner import AgentRunner
from ContractCoding.utils.log import get_logger
from ContractCoding.utils.state import GeneralState


ACTIONABLE_STATUS_VALUES = {"TODO", "IN_PROGRESS", "ERROR"}
IMPLEMENTED_STATUS_VALUES = {"DONE", "VERIFIED"}
VALID_STATUS_VALUES = ACTIONABLE_STATUS_VALUES | IMPLEMENTED_STATUS_VALUES


class GraphTraverser:
    def __init__(
        self,
        config: Config,
        agent_runner: AgentRunner,
        memory_processor: MemoryProcessor,
        document_manager: DocumentManager,
    ):
        self.config = config
        self.logger = get_logger(config.LOG_PATH)
        self.agent_runner = agent_runner
        self.memory_processor = memory_processor
        self.termination_policy = self.config.TERMINATION_POLICY
        self.document_manager = document_manager

    def traverse(
        self, start_agent: str, initial_states: Any
    ) -> Tuple[List[Dict[str, List[GeneralState]]], List[Tuple[str, str]], List[GeneralState]]:
        execution_trace: List[Tuple[str, str]] = []
        initial_state_list = initial_states if isinstance(initial_states, list) else [initial_states]
        all_layers: List[Dict[str, List[GeneralState]]] = [{start_agent: initial_state_list}]
        terminating_states: List[GeneralState] = []

        while all_layers[-1] and len(all_layers) <= self.config.MAX_LAYERS:
            current_level_agents = all_layers[-1]
            layer_index = len(all_layers) - 1

            base_version = self.document_manager.get_version()
            try:
                self.document_manager.begin_layer_aggregation(base_version)
            except Exception:
                pass

            layer_output_states: Dict[str, List[GeneralState]] = defaultdict(list)

            def _run_single(agent_name: str, state: GeneralState) -> GeneralState:
                next_available_agents = self.agent_runner.agents
                print(f"--- Current Agent: {agent_name} ---")
                self.logger.info(f"--- Current Agent: {agent_name} | Sub Task: {state.sub_task} ---")
                output_state = self.agent_runner.run(
                    agent_name=agent_name,
                    state=state,
                    next_available_agents=next_available_agents,
                )
                self.memory_processor.add_message(agent_name, output_state)
                execution_trace.append((agent_name, "NEXT_LAYER"))
                return output_state

            max_workers = getattr(self.config, "MAX_WORKERS", 16)
            with ThreadPoolExecutor(max_workers=max_workers) as executor:
                futures = {}
                for agent_name, states in current_level_agents.items():
                    for state in states:
                        futures[executor.submit(_run_single, agent_name, state)] = (agent_name, state)

                for future in as_completed(futures):
                    agent_name, fallback_state = futures[future]
                    try:
                        output_state = future.result()
                        layer_output_states[agent_name].append(output_state)
                    except Exception as e:
                        self.logger.error(f"Agent {agent_name} failed with error: {e}")
                        layer_output_states[agent_name].append(fallback_state)

            try:
                self.document_manager.commit_layer_aggregation()
            except Exception as e:
                self.logger.error(f"Document layer aggregation commit failed: {e}")

            next_level_agents_map = defaultdict(list)
            doc_content = self.document_manager.get()

            if layer_index == 0:
                next_agent = "Architect"
                task_msg = (
                    "Contract review ONLY (no implementation review). Review and repair the Project Plan and Architecture generated by Project Manager. "
                    "Ensure contracts are clear, complete, internally consistent, and describe end-to-end runnable flows. "
                    "Think in module cells first: for API projects use bounded subsystems, and for algorithm projects use function clusters / solver stages / dataflow stages. "
                    "Do NOT set any file Status to VERIFIED or DONE during this phase. "
                    "If the contract has blocking issues, set the affected file blocks to ERROR and append actionable issue bullets after the Status line."
                )

                is_valid, validation_errors = self._validate_project_structure(doc_content)
                if not is_valid:
                    self.logger.warning(f"--- Document Validation Failed: {validation_errors} ---")
                    self.logger.info("--- Fallback: Scheduling Project_Manager to fix document structure ---")
                    pm_msg = (
                        "Critical: The Collaborative Document is incomplete. "
                        f"The following issues must be fixed before execution: {validation_errors}. "
                        "You MUST repair the contract using `document_action`, and make sure each file block has a concrete Module / Owner / Status."
                    )

                    pm_state = list(current_level_agents.values())[0][0]
                    new_state = GeneralState(
                        task=pm_state.task,
                        sub_task=pm_msg,
                        role="user",
                        thinking="",
                        output="",
                    )
                    next_level_agents_map["Project_Manager"].append(new_state)
                else:
                    pm_state = list(current_level_agents.values())[0][0]
                    new_state = GeneralState(
                        task=pm_state.task,
                        sub_task=task_msg,
                        role="user",
                        thinking="",
                        output="",
                    )
                    next_level_agents_map[next_agent].append(new_state)
            else:
                next_level_agents_map = self._schedule_from_contract(doc_content, current_level_agents)

            if not next_level_agents_map:
                modules = self._parse_modules(doc_content)
                pending_tasks = [
                    task
                    for module in modules
                    for task in module["tasks"]
                    if task["status"] != "VERIFIED"
                ]

                if not pending_tasks:
                    terminal_source = layer_output_states or current_level_agents
                    for states in terminal_source.values():
                        terminating_states.extend(states)
                    break

                in_progress_modules = [
                    module
                    for module in modules
                    if any(task["status"] == "IN_PROGRESS" for task in module["tasks"])
                ]
                if in_progress_modules and not next_level_agents_map:
                    base_state = self._select_base_state(layer_output_states, current_level_agents)
                    next_level_agents_map = self._schedule_in_progress_modules(in_progress_modules, base_state)

                if not next_level_agents_map:
                    pm_msg = (
                        "Critical: The workflow has stalled. There are pending module cells but no agents were scheduled. "
                        "Please review the contract, especially Module / Depends On / Execution fields and the Symbolic API Specifications."
                    )
                    base_state = self._select_base_state(layer_output_states, current_level_agents)
                    new_state = base_state.model_copy()
                    new_state.sub_task = pm_msg
                    next_level_agents_map["Project_Manager"].append(new_state)

            next_layer_plan = {k: len(v) for k, v in next_level_agents_map.items()}
            print(f"--- Next Layer Agents: {next_layer_plan} ---")
            self.logger.info(f"--- Next Layer Plan: {next_layer_plan} ---")
            all_layers.append(next_level_agents_map)

        return all_layers, execution_trace, terminating_states

    def _select_base_state(
        self,
        output_states: Dict[str, List[GeneralState]],
        fallback_states: Dict[str, List[GeneralState]],
    ) -> GeneralState:
        for states in output_states.values():
            if states:
                return states[0]
        for states in fallback_states.values():
            if states:
                return states[0]
        return GeneralState()

    def _validate_project_structure(self, content: str) -> Tuple[bool, List[str]]:
        validation_errors = self.document_manager.validate_contract_structure()
        if validation_errors:
            return False, validation_errors
        return True, []

    def _parse_contract(self, content: str) -> List[Dict[str, object]]:
        return self.document_manager.get_tasks()

    def _parse_modules(self, content: str) -> List[Dict[str, object]]:
        return self.document_manager.get_modules()

    def _extract_issues_from_task(self, task: Dict[str, object]) -> str:
        block = task.get("block", "") or ""
        if not block:
            return ""

        lines = block.split("\n")
        status_idx = None
        for index, line in enumerate(lines):
            if re.search(r"\*\*Status(?::)?\*\*", line):
                status_idx = index
                break
        if status_idx is None:
            return ""

        tail = [line.rstrip() for line in lines[status_idx + 1 :]]
        tail = [line for line in tail if line.strip()]
        if not tail:
            return ""

        issues: List[str] = []
        for line in tail:
            if re.search(
                r"\*\*(Owner|Version|Status|Module(?:\s*Cell)?|Depends On|Dependencies|Execution(?: Mode)?|Class|Function|Methods|Attributes)\*\*",
                line,
            ):
                continue
            issues.append(line)
        return "\n".join(issues).strip()

    def _extract_contract_description_from_task(self, task: Dict[str, object], max_lines: int = 30) -> str:
        block = (task.get("block", "") or "").strip("\n")
        if not block:
            return ""

        skip_fields = re.compile(
            r"\*\*\s*(Owner|Version|Status|Module(?:\s*Cell)?|Depends On|Dependencies|Execution(?: Mode)?)\s*:?\s*\*\*",
            re.IGNORECASE,
        )
        lines: List[str] = []
        for raw_line in block.split("\n"):
            line = raw_line.rstrip()
            if not line.strip():
                continue
            if line.strip().startswith("**File:**"):
                continue
            if skip_fields.search(line):
                continue
            lines.append(line)
            if len(lines) >= max_lines:
                break
        return "\n".join(lines).strip()

    @staticmethod
    def _task_is_actionable(task: Dict[str, object]) -> bool:
        return str(task.get("status", "TODO")) in ACTIONABLE_STATUS_VALUES

    @staticmethod
    def _task_is_done(task: Dict[str, object]) -> bool:
        return str(task.get("status", "TODO")) in IMPLEMENTED_STATUS_VALUES

    def _module_is_implemented(self, module: Dict[str, object]) -> bool:
        tasks = module.get("tasks", [])
        return bool(tasks) and all(self._task_is_done(task) for task in tasks)

    def _module_is_review_ready(self, module: Dict[str, object]) -> bool:
        tasks = module.get("tasks", [])
        return bool(tasks) and any(str(task.get("status")) == "DONE" for task in tasks) and all(
            self._task_is_done(task) for task in tasks
        )

    def _module_dependencies_satisfied(
        self,
        module: Dict[str, object],
        module_index: Dict[str, Dict[str, object]],
    ) -> bool:
        for dependency in module.get("dependencies", []) or []:
            dependency_module = module_index.get(str(dependency))
            if dependency_module and not self._module_is_implemented(dependency_module):
                return False
        return True

    def _task_dependencies_satisfied(
        self,
        task: Dict[str, object],
        task_index: Dict[str, Dict[str, object]],
        module_index: Dict[str, Dict[str, object]],
    ) -> bool:
        for dependency in task.get("depends_on", []) or []:
            dependency_ref = str(dependency)
            if dependency_ref in task_index and not self._task_is_done(task_index[dependency_ref]):
                return False
            if dependency_ref in module_index and not self._module_is_implemented(module_index[dependency_ref]):
                return False
        return True

    def _select_owner_packets(
        self,
        module: Dict[str, object],
        ready_tasks: List[Dict[str, object]],
    ) -> Dict[str, List[Dict[str, object]]]:
        if not ready_tasks:
            return {}

        execution_mode = str(module.get("execution_mode", "single"))
        if execution_mode == "single":
            first_task = ready_tasks[0]
            owner = str(first_task.get("owner", "Unknown"))
            return {owner: [first_task]} if owner != "Unknown" else {}

        owner_packets: Dict[str, List[Dict[str, object]]] = defaultdict(list)
        for task in ready_tasks:
            owner = str(task.get("owner", "Unknown"))
            if owner == "Unknown":
                continue
            owner_packets[owner].append(task)
        return dict(owner_packets)

    def _build_module_execution_message(
        self,
        module: Dict[str, object],
        owner: str,
        owner_tasks: List[Dict[str, object]],
    ) -> str:
        primary_task = owner_tasks[0]
        primary_target = str(primary_task.get("file", ""))
        module_name = str(module.get("module", "Unknown Module"))
        module_dependencies = module.get("dependencies", []) or []

        task_sections: List[str] = []
        for task in owner_tasks:
            file_path = str(task.get("file", "Unknown"))
            status = str(task.get("status", "TODO"))
            summary = self._extract_contract_description_from_task(task)
            issues = self._extract_issues_from_task(task) if status == "ERROR" else ""
            section_lines = [
                f"Assigned file: `{file_path}`",
                f"Current Status: {status}",
                "Contract summary:",
                summary or "(No additional summary provided in the contract.)",
            ]
            if issues:
                section_lines.extend(
                    [
                        "Contract issues to resolve:",
                        issues,
                    ]
                )
            task_sections.append("\n".join(section_lines))

        target_file_list = "\n".join(f"- `{task['file']}`" for task in owner_tasks)
        dependency_section = (
            "\n".join(f"- `{dependency}`" for dependency in module_dependencies)
            if module_dependencies
            else "- None"
        )

        return (
            f"Module Cell: {module_name}\n"
            f"Execution Mode: {module.get('execution_mode', 'single')}\n"
            f"Owner Role: {owner}\n"
            f"Primary target file: `{primary_target}`\n"
            "Assigned files in this module packet:\n"
            f"{target_file_list}\n\n"
            "Satisfied module dependencies:\n"
            f"{dependency_section}\n\n"
            "Implement/Fix the assigned files for this module cell. Work within this module packet first, keep logic real (no placeholders), and update the same file blocks to DONE via <document_action>.\n\n"
            + "\n\n".join(task_sections)
        )

    def _build_module_review_message(self, module: Dict[str, object]) -> str:
        module_name = str(module.get("module", "Unknown Module"))
        files = [str(task.get("file", "Unknown")) for task in module.get("tasks", [])]
        file_list = "\n".join(f"- `{file_path}`" for file_path in files)
        return (
            f"Module Cell: {module_name}\n"
            "Review Mode: module_completion\n"
            "The following module cell has completed implementation and is ready for validation.\n\n"
            "Files to review:\n"
            f"{file_list}\n\n"
            "Review all listed files together as one module cell. Compare the implementation against the contract, verify imports / call chains / runtime wiring, and then update statuses via <document_action>. "
            "If a file is correct, set it to VERIFIED. If a file is incorrect, set it to ERROR and append actionable issue bullets in the same file block."
        )

    def _schedule_module_packets(
        self,
        modules: List[Dict[str, object]],
        base_state: GeneralState,
    ) -> Dict[str, List[GeneralState]]:
        next_agents_map = defaultdict(list)
        module_index = {str(module["module"]): module for module in modules}
        task_index = {
            str(task["file"]): task
            for module in modules
            for task in module.get("tasks", [])
        }

        for module in modules:
            if not self._module_dependencies_satisfied(module, module_index):
                continue

            ready_tasks = [
                task
                for task in module.get("tasks", [])
                if self._task_is_actionable(task) and self._task_dependencies_satisfied(task, task_index, module_index)
            ]
            owner_packets = self._select_owner_packets(module, ready_tasks)
            for owner, owner_tasks in owner_packets.items():
                new_state = base_state.model_copy()
                new_state.sub_task = self._build_module_execution_message(module, owner, owner_tasks)
                next_agents_map[owner].append(new_state)

        for module in modules:
            if not self._module_is_review_ready(module):
                continue
            review_msg = self._build_module_review_message(module)
            critic_state = base_state.model_copy()
            critic_state.sub_task = review_msg
            next_agents_map["Critic"].append(critic_state)

            reviewer_state = base_state.model_copy()
            reviewer_state.sub_task = review_msg
            next_agents_map["Code_Reviewer"].append(reviewer_state)

        return next_agents_map

    def _schedule_in_progress_modules(
        self,
        modules: List[Dict[str, object]],
        base_state: GeneralState,
    ) -> Dict[str, List[GeneralState]]:
        next_agents_map = defaultdict(list)
        for module in modules:
            owner_packets = self._select_owner_packets(
                module,
                [task for task in module.get("tasks", []) if str(task.get("status")) == "IN_PROGRESS"],
            )
            for owner, owner_tasks in owner_packets.items():
                new_state = base_state.model_copy()
                new_state.sub_task = self._build_module_execution_message(module, owner, owner_tasks)
                next_agents_map[owner].append(new_state)
        return next_agents_map

    def _schedule_from_contract(
        self, doc_content: str, current_layer_agents: Dict[str, List[GeneralState]]
    ) -> Dict[str, List[GeneralState]]:
        next_agents_map = defaultdict(list)
        base_state = list(current_layer_agents.values())[0][0]

        validation_errors = self.document_manager.validate_contract_structure()
        if validation_errors:
            pm_msg = (
                "Critical: The Collaborative Document is incomplete. "
                "Fix these issues using `document_action` before execution continues: "
                f"{validation_errors}"
            )
            new_state = base_state.model_copy()
            new_state.sub_task = pm_msg
            next_agents_map["Project_Manager"].append(new_state)
            return next_agents_map

        tasks = self._parse_contract(doc_content)
        if not tasks:
            pm_msg = (
                "Critical: The system could not parse any tasks from the 'Symbolic API Specifications'. "
                "Please ensure the document follows the correct format with '**File:**', '**Owner:**', and '**Status:**' fields."
            )
            new_state = base_state.model_copy()
            new_state.sub_task = pm_msg
            next_agents_map["Project_Manager"].append(new_state)
            return next_agents_map

        incomplete_tasks = []
        for task in tasks:
            file_path = str(task.get("file", "Unknown"))
            owner = str(task.get("owner", "Unknown"))
            status = str(task.get("status", "TODO"))
            missing_fields = []
            if owner == "Unknown":
                missing_fields.append("Owner")
            if status not in VALID_STATUS_VALUES:
                missing_fields.append(f"Status({status})")
            if missing_fields and file_path != "Unknown":
                incomplete_tasks.append(f"{file_path}: {', '.join(missing_fields)}")

        if incomplete_tasks:
            pm_msg = (
                "Critical: The Collaborative Document has incomplete sub-tasks. "
                f"Fix these file blocks to include valid Owner / Status values: {incomplete_tasks}. "
                "You MUST fix the document using `document_action`."
            )
            new_state = base_state.model_copy()
            new_state.sub_task = pm_msg
            next_agents_map["Project_Manager"].append(new_state)
            return next_agents_map

        modules = self._parse_modules(doc_content)
        if not modules:
            pm_msg = (
                "Critical: The system could not derive any module cells from the contract. "
                "Add explicit **Module:** fields to the Symbolic API Specifications, or provide enough structure for the scheduler to infer them."
            )
            new_state = base_state.model_copy()
            new_state.sub_task = pm_msg
            next_agents_map["Project_Manager"].append(new_state)
            return next_agents_map

        return self._schedule_module_packets(modules, base_state)


Orchestrator = GraphTraverser
