from collections import defaultdict
from concurrent.futures import ThreadPoolExecutor, as_completed
import re
from typing import Any, Dict, List, Tuple

from MetaFlow.config import Config
from MetaFlow.memory.audit import check_missing_specs
from MetaFlow.memory.document import DocumentManager
from MetaFlow.memory.processor import MemoryProcessor
from MetaFlow.orchestration.runner import AgentRunner
from MetaFlow.utils.log import get_logger
from MetaFlow.utils.state import GeneralState


class GraphTraverser:
    def __init__(
        self,
        config: Config,
        agent_runner: AgentRunner,
        memory_processor: MemoryProcessor,
        document_manager: DocumentManager,
    ):
        self.config = config
        self.logger = get_logger(config.LOG_PATH)
        self.agent_runner = agent_runner
        self.memory_processor = memory_processor
        self.termination_policy = self.config.TERMINATION_POLICY
        self.document_manager = document_manager

    def traverse(
        self, start_agent: str, initial_states: Any
    ) -> Tuple[List[Dict[str, List[GeneralState]]], List[Tuple[str, str]], List[GeneralState]]:
        execution_trace: List[Tuple[str, str]] = []
        initial_state_list = initial_states if isinstance(initial_states, list) else [initial_states]
        all_layers: List[Dict[str, List[GeneralState]]] = [{start_agent: initial_state_list}]
        terminating_states: List[GeneralState] = []

        executed_agents_history = []

        while all_layers[-1] and len(all_layers) <= self.config.MAX_LAYERS:
            current_level_agents = all_layers[-1]
            layer_index = len(all_layers) - 1

            base_version = self.document_manager.get_version()
            try:
                self.document_manager.begin_layer_aggregation(base_version)
            except Exception:
                pass

            layer_executed_agents = []

            def _run_single(agent_name: str, state: GeneralState) -> None:
                next_available_agents = self.agent_runner.agents
                print(f"--- Current Agent: {agent_name} ---")
                self.logger.info(f"--- Current Agent: {agent_name} | Sub Task: {state.sub_task} ---")
                output_state = self.agent_runner.run(
                    agent_name=agent_name,
                    state=state,
                    next_available_agents=next_available_agents,
                )
                self.memory_processor.add_message(agent_name, output_state)
                execution_trace.append((agent_name, "NEXT_LAYER"))

            max_workers = getattr(self.config, "MAX_WORKERS", 16)
            with ThreadPoolExecutor(max_workers=max_workers) as executor:
                futures = {}
                for agent_name, states in current_level_agents.items():
                    for state in states:
                        futures[executor.submit(_run_single, agent_name, state)] = agent_name

                for future in as_completed(futures):
                    agent_name = futures[future]
                    layer_executed_agents.append(agent_name)
                    try:
                        future.result()
                    except Exception as e:
                        self.logger.error(f"Agent {agent_name} failed with error: {e}")

            try:
                self.document_manager.commit_layer_aggregation()
            except Exception as e:
                self.logger.error(f"Document layer aggregation commit failed: {e}")

            executed_agents_history.append(set(layer_executed_agents))

            next_level_agents_map = defaultdict(list)
            doc_content = self.document_manager.get()

            if layer_index == 0:
                next_agent = "Critic"
                task_msg = (
                    "Contract review ONLY (no implementation review). Review the Project Plan and Architecture generated by Project Manager. "
                    "Ensure contracts are clear, complete, and internally consistent. "
                    "Do NOT set any file Status to VERIFIED or DONE during this phase. "
                    "If the contract has blocking issues, set the affected file blocks to ERROR and append actionable issue bullets after the Status line."
                )

                is_valid, validation_errors = self._validate_project_structure(doc_content)
                if not is_valid:
                    self.logger.warning(f"--- Document Validation Failed: {validation_errors} ---")
                    self.logger.info("--- Fallback: Scheduling Project_Manager to fix document structure ---")
                    pm_msg = f"Critical: The Collaborative Document is incomplete. The following files listed in 'Project Structure' are missing from 'Sub-Tasks' or lack required fields: {validation_errors}. You MUST fix the document using `document_action` to add detailed sub-tasks for these files."

                    pm_state = list(current_level_agents.values())[0][0]
                    new_state = GeneralState(
                        task=pm_state.task,
                        sub_task=pm_msg,
                        role="user",
                        thinking="",
                        output="",
                    )
                    next_level_agents_map["Project_Manager"].append(new_state)
                else:
                    pm_state = list(current_level_agents.values())[0][0]
                    new_state = GeneralState(
                        task=pm_state.task,
                        sub_task=task_msg,
                        role="user",
                        thinking="",
                        output="",
                    )
                    next_level_agents_map[next_agent].append(new_state)

            elif layer_index == 1:
                next_level_agents_map = self._schedule_from_contract(doc_content, current_level_agents)
            else:
                next_level_agents_map = self._schedule_from_contract(doc_content, current_level_agents)

            if not next_level_agents_map:
                pending_tasks = [t for t in self._parse_contract(doc_content) if t['status'] != 'VERIFIED']

                if not pending_tasks:
                    for states in current_level_agents.values():
                        terminating_states.extend(states)
                    break
                else:
                    in_progress_tasks = [t for t in pending_tasks if t['status'] == 'IN_PROGRESS']

                    if in_progress_tasks and not next_level_agents_map:
                        base_state = list(current_level_agents.values())[0][0]
                        for task in in_progress_tasks:
                            owner = task['owner']
                            file_path = task['file']
                            if owner != "Unknown":
                                msg = f"Continue implementation of {file_path}. Current Status: IN_PROGRESS. You MUST complete the logic."
                                new_state = base_state.model_copy()
                                new_state.sub_task = msg
                                next_level_agents_map[owner].append(new_state)

                    if not next_level_agents_map:
                        pm_msg = "Critical: The workflow has stalled. There are pending tasks but no agents were scheduled. Please review the 'Symbolic API Specifications' in the document. Ensure all files have valid Status (TODO, IN_PROGRESS, DONE, VERIFIED) and Owners."
                        base_state = list(current_level_agents.values())[0][0]
                        new_state = base_state.model_copy()
                        new_state.sub_task = pm_msg
                        next_level_agents_map["Project_Manager"].append(new_state)

            next_layer_plan = {k: len(v) for k, v in next_level_agents_map.items()}
            print(f"--- Next Layer Agents: {next_layer_plan} ---")
            self.logger.info(f"--- Next Layer Plan: {next_layer_plan} ---")
            all_layers.append(next_level_agents_map)

        return all_layers, execution_trace, terminating_states

    def _validate_project_structure(self, content: str) -> Tuple[bool, List[str]]:
        validation_errors = []

        missing_specs = check_missing_specs(content)
        if missing_specs:
            validation_errors.extend(
                [
                    f"File defined in Project Structure but missing from Sub-Tasks (Symbolic API Specifications): {f}"
                    for f in missing_specs
                ]
            )

        parsed_tasks = self._parse_contract(content)
        for t in parsed_tasks:
            file_path = t.get('file', 'Unknown')
            if t.get('owner', 'Unknown') == 'Unknown':
                validation_errors.append(f"Task for {file_path} missing 'Owner' field.")

            status = t.get('status', 'TODO')
            if status not in ['TODO', 'IN_PROGRESS', 'ERROR', 'DONE', 'VERIFIED']:
                validation_errors.append(f"Task for {file_path} has invalid Status: {status}")

        if validation_errors:
            return False, validation_errors

        return True, []

    def _parse_contract(self, content: str) -> List[Dict[str, str]]:
        tasks = []
        lines = content.split('\n')
        current_task: Dict[str, str] = {}
        current_block_lines: List[str] = []

        def _finalize_current_task():
            nonlocal current_task, current_block_lines
            if not (current_task and 'file' in current_task):
                current_task = {}
                current_block_lines = []
                return
            if 'owner' not in current_task:
                current_task['owner'] = 'Unknown'
            if 'status' not in current_task:
                current_task['status'] = 'TODO'
            current_task['block'] = "\n".join(current_block_lines).strip("\n")
            tasks.append(current_task)
            current_task = {}
            current_block_lines = []

        for line in lines:
            line = line.strip()

            file_match = re.search(r"\*\*File:\*\*\s*`?([^`]+)`?", line)
            header_match = re.match(r"^####\s+`?([\w./-]+)`?", line)
            paths_match = re.search(r"\*\*Paths\*\*:\s*`?([^`]+)`?", line)
            path_match = re.search(r"\*\*Path\*\*:\s*`?([^`]+)`?", line)

            new_file_path = None
            if file_match:
                new_file_path = file_match.group(1).strip()
            elif header_match:
                new_file_path = header_match.group(1).strip()
            elif paths_match:
                new_file_path = paths_match.group(1).strip()
            elif path_match:
                new_file_path = path_match.group(1).strip()

            if new_file_path:
                _finalize_current_task()
                current_task = {'file': new_file_path}
                current_block_lines = [f"**File:** `{new_file_path}`"]
                continue

            if current_task:
                current_block_lines.append(line)

            owner_match = re.search(r"\*\*Owner(?::)?\*\* [:]?\s*(.+)", line)
            if owner_match and current_task:
                owner_clean = owner_match.group(1).strip().lstrip(':').strip()
                owner_clean = owner_clean.replace(" ", "_")
                current_task['owner'] = owner_clean

            status_match = re.search(r"\*\*Status(?::)?\*\* [:]?\s*(.+)", line)
            if status_match and current_task:
                raw_status = status_match.group(1).strip().lstrip(':').strip()
                if "TBD" in raw_status.upper() or not raw_status:
                    current_task['status'] = "TODO"
                else:
                    current_task['status'] = raw_status

        _finalize_current_task()

        return tasks

    def _extract_issues_from_task(self, task: Dict[str, str]) -> str:
        block = task.get('block', '') or ''
        if not block:
            return ''

        lines = block.split('\n')
        status_idx = None
        for i, ln in enumerate(lines):
            if re.search(r"\*\*Status(?::)?\*\*", ln):
                status_idx = i
                break
        if status_idx is None:
            return ''

        tail = [ln.rstrip() for ln in lines[status_idx + 1 :]]
        tail = [ln for ln in tail if ln.strip()]
        if not tail:
            return ''

        issues: List[str] = []
        for ln in tail:
            if re.search(r"\*\*(Owner|Version|Status|Class|Function|Methods|Attributes)\*\*", ln):
                continue
            issues.append(ln)
        return "\n".join(issues).strip()

    def _schedule_from_contract(
        self, doc_content: str, current_layer_agents: Dict[str, List[GeneralState]]
    ) -> Dict[str, List[GeneralState]]:
        missing_specs = check_missing_specs(doc_content)
        next_agents_map = defaultdict(list)

        base_state = list(current_layer_agents.values())[0][0]

        if missing_specs:
            pm_msg = f"Critical: The Collaborative Document is incomplete. The following files listed in 'Project Structure' are missing from 'Sub-Tasks' or lack required fields: {missing_specs}. You MUST fix the document using `document_action` to add detailed sub-tasks for these files."
            new_state = base_state.model_copy()
            new_state.sub_task = pm_msg
            next_agents_map["Project_Manager"].append(new_state)
            return next_agents_map

        tasks = self._parse_contract(doc_content)
        if not tasks:
            pm_msg = "Critical: The system could not parse any tasks from the 'Symbolic API Specifications'. Please ensure the document follows the correct format with '**File:**', '**Owner:**', and '**Status:**' fields."
            new_state = base_state.model_copy()
            new_state.sub_task = pm_msg
            next_agents_map["Project_Manager"].append(new_state)
            return next_agents_map

        incomplete_tasks = []
        for t in tasks:
            file_path = t.get('file', 'Unknown')
            owner = t.get('owner', 'Unknown')
            status = t.get('status', 'TODO')
            missing_fields = []
            if owner == 'Unknown':
                missing_fields.append('Owner')
            if status not in ['TODO', 'IN_PROGRESS', 'ERROR', 'DONE', 'VERIFIED']:
                missing_fields.append(f"Status({status})")
            if missing_fields and file_path != 'Unknown':
                incomplete_tasks.append(f"{file_path}: {', '.join(missing_fields)}")

        if incomplete_tasks:
            pm_msg = (
                "Critical: The Collaborative Document has incomplete sub-tasks (missing required fields). "
                f"Fix these file blocks to include **Owner:** and **Status:** (and keep them consistent): {incomplete_tasks}. "
                "You MUST fix the document using `document_action`."
            )
            new_state = base_state.model_copy()
            new_state.sub_task = pm_msg
            next_agents_map["Project_Manager"].append(new_state)
            return next_agents_map

        done_tasks: List[Dict[str, str]] = []

        for task in tasks:
            file_path = task['file']
            owner = task['owner']
            status = task['status']

            if owner == "Unknown":
                continue

            if status in ['TODO', 'IN_PROGRESS', 'ERROR']:
                issue_text = ""
                if status == 'ERROR':
                    issue_text = self._extract_issues_from_task(task)

                if issue_text:
                    msg = (
                        f"Fix {file_path}. Current Status: {status}. Follow the contract strictly.\n\n"
                        "Contract issues to resolve (from the file block):\n"
                        f"{issue_text}\n\n"
                        "After fixes, update the same file block status to DONE via <document_action>."
                    )
                else:
                    msg = f"Implement/Fix {file_path}. Current Status: {status}. Follow the contract strictly."
                new_state = base_state.model_copy()
                new_state.sub_task = msg
                next_agents_map[owner].append(new_state)

            elif status == 'DONE':
                done_tasks.append(task)

        if done_tasks:
            files = [t.get('file', 'Unknown') for t in done_tasks if t.get('file')]
            files = [f for f in files if f != 'Unknown']
            file_list = "\n".join([f"- {f}" for f in files])
            review_msg = (
                "Batch review the following completed tasks (Status: DONE). "
                "For EACH file, read the implementation, compare against the contract, and then update the document status. "
                "If correct: set Status to VERIFIED. If incorrect: set Status to ERROR and delegate fixes with clear instructions. "
                "You MUST use the `document_action` tool to update statuses (do not only describe in text).\n\n"
                "Files to review:\n"
                f"{file_list}"
            )

            critic_state = base_state.model_copy()
            critic_state.sub_task = review_msg
            next_agents_map["Critic"].append(critic_state)

            reviewer_state = base_state.model_copy()
            reviewer_state.sub_task = review_msg
            next_agents_map["Code_Reviewer"].append(reviewer_state)

        return next_agents_map


Orchestrator = GraphTraverser
